name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Astro check
        run: pnpm check:astro

      - name: Type check
        run: pnpm type-check

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format:check

      - name: Unit tests
        run: pnpm test -- --reporter=default

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: E2E tests (Playwright)
        id: e2e
        run: pnpm test:e2e
        continue-on-error: true

      - name: Upload Playwright HTML report
        if: steps.e2e.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore

      - name: Fail job if E2E failed
        if: steps.e2e.outcome == 'failure'
        run: exit 1

