name: Commitlint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  commitlint:
    name: Lint commit messages in PR
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run commitlint on PR commits
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.js
