name: PR Checks
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  node-checks:
    name: Node.js Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm -s tsc --noEmit

      - name: Astro check
        run: pnpm -s astro check

      - name: Test
        run: pnpm -s test

      - name: Build
        run: pnpm -s astro build

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run e2e tests
        run: pnpm -s test:e2e

  container-smoke-test:
    name: Container Smoke Test
    needs:
      - node-checks
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: portfolio-test:latest
          load: true

      - name: Run container and test
        run: |
          docker run -d --name portfolio-test -p 8080:8080 portfolio-test:latest
          for i in {1..30}; do
            code=$(curl -fsS -o /dev/null -w "%{http_code}" http://localhost:8080/ || true)
            [ "$code" = "200" ] && echo "✅ 200 OK" && break
            [ $i -eq 30 ] && echo "❌ no 200 after 30 tries" && docker logs portfolio-test && exit 1
            sleep 2
          done

      - name: Clean up container
        if: always()
        run: |
          docker rm -f portfolio-test || true
          docker rmi portfolio-test:latest || true
