name: PR Checks
permissions:
  contents: read

on:
  pull_request:
    branches: [main]

concurrency:
  group: pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  node-checks:
    name: Node.js Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm -s lint

      - name: Format check
        run: pnpm -s format:check

      - name: Type check
        run: pnpm -s tsc --noEmit

      - name: Astro check
        run: pnpm -s astro check

      - name: Test
        run: pnpm -s test

      - name: Build
        run: pnpm -s astro build

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run e2e tests
        env:
          PLAYWRIGHT_COLOR_SCHEME: light
        run: pnpm -s test:e2e

  container-smoke-test:
    name: Container Smoke Test
    needs:
      - node-checks
      - e2e-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: docker/setup-buildx-action@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          tags: portfolio-test:latest
          load: true

      - name: Run container and test
        run: |
          docker run -d --name portfolio-test -p 8080:8080 portfolio-test:latest
          pnpm -s smoke -- --url http://localhost:8080 --stability-checks 3 --timeout 60

      - name: Clean up container
        if: always()
        run: |
          docker rm -f portfolio-test || true
          docker rmi portfolio-test:latest || true
