name: release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      
      - uses: pnpm/action-setup@v4

      - name: Enable Corepack
        run: corepack enable
      
      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint, type, and format checks
        run: pnpm -s check

      - name: Run unit tests
        run: pnpm -s test

      - name: Build site
        run: pnpm -s build

      - name: Semantic Release
        id: sr
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: img
        run: echo "IMAGE=ghcr.io/${GITHUB_REPOSITORY_OWNER}/portfolio" >> $GITHUB_OUTPUT

      - name: Build metadata
        id: meta
        run: echo "NOW=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

      - name: Derive short SHA
        id: sha
        run: echo "SHORT=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute semver tags
        if: steps.sr.outputs.new_release_published == 'true'
        id: sv
        run: |
          VER="${{ steps.sr.outputs.new_release_version }}"
          echo "MAJOR=${VER%%.*}" >> $GITHUB_OUTPUT
          echo "MINOR=${VER%.*}" >> $GITHUB_OUTPUT

      - name: Build & push image
        if: steps.sr.outputs.new_release_published == 'true' && steps.sr.outputs.new_release_channel == ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sr.outputs.new_release_version }}
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sv.outputs.MINOR }}
            ${{ steps.img.outputs.IMAGE }}:${{ steps.sv.outputs.MAJOR }}
            ${{ steps.img.outputs.IMAGE }}:latest
            ${{ steps.img.outputs.IMAGE }}:sha-${{ steps.sha.outputs.SHORT }}
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ steps.meta.outputs.NOW }}
            org.opencontainers.image.version=${{ steps.sr.outputs.new_release_version }}
            org.opencontainers.image.title=portfolio
            org.opencontainers.image.description=Astro portfolio site
            org.opencontainers.image.url=https://github.com/yamshy/portfolio
            org.opencontainers.image.documentation=https://github.com/yamshy/portfolio#readme
          cache-from: type=gha
          cache-to: type=gha,mode=max