name: release

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  packages: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Semantic Release
        id: sr
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/github
            @semantic-release/npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Compute semver tags
        if: steps.sr.outputs.new_release_published == 'true'
        id: sv
        run: |
          VER="${{ steps.sr.outputs.new_release_version }}"
          echo "MAJOR=${VER%%.*}" >> $GITHUB_OUTPUT
          echo "MINOR=${VER%.*}" >> $GITHUB_OUTPUT

      - name: Build & push image
        if: steps.sr.outputs.new_release_published == 'true' && steps.sr.outputs.new_release_channel == ''
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ steps.sr.outputs.new_release_version }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ steps.sv.outputs.MINOR }}
            ghcr.io/${{ github.repository_owner }}/portfolio:${{ steps.sv.outputs.MAJOR }}
            ghcr.io/${{ github.repository_owner }}/portfolio:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.created=${{ github.event.head_commit.timestamp }}
            org.opencontainers.image.version=${{ steps.sr.outputs.new_release_version }}
            org.opencontainers.image.description=Astro portfolio site
          cache-from: type=gha
          cache-to: type=gha,mode=max